services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
#    volumes:
#      - ./:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8080

networks:
  default:
    driver: bridge
