name: Deploy WASM to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          echo "EMSDK_ENV activated"
      - name: Build WASM
        run: |
          source emsdk/emsdk_env.sh
          # create a modified websockets.js with the correct url
          sed -i "s|const websocket_url = \"wss://localhost:3000/ws\"|const websocket_url = \"$WEBSOCKET_URL\"|g" html_template/websockets.js
          # build wasm
          emcc main.cpp -s WASM=1 -s USE_SDL=2 -O3 -s ASYNCIFY -s \
          NO_EXIT_RUNTIME=1 -s EXPORTED_RUNTIME_METHODS=['ccall'] \
          -s EMBIND_STD_STRING_IS_UTF8=0 \
          -lembind \
          --shell-file html_template/template.html -o index.html

          ls -la
        env:
          WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
